adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: ${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    consumer:
          topic: "test"

spring:
  kafka:
    consumer:
      bootstrap-servers:
        - "localhost:9092"
        - "localhost:9094"
      group-id: "client-service"
    producer:
      bootstrap-servers:
        - "localhost:9092"
        - "localhost:9094"
      client-id: "client-service"